on: [ push, pull_request ]

jobs:
    deployment_keys_demo:
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, macOS-latest, windows-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup key
                uses: ./
                with:
                    ssh-private-key: |                        
                        ${{secrets.SSH_AZR}}
            -   run: |
                    git clone git@ssh.dev.azure.com:v3/rakeshrakshit/USDesk/USDeskForJava

    docker_demo:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:latest
        steps:
            -   uses: actions/checkout@v3
            -   run: apt update && apt install -y openssh-client git
            -   name: Setup key
                uses: ./
                with:
                    ssh-private-key: |
                        ${{ secrets.SSH_AZR }}
            -   run: |
                    git clone git@ssh.dev.azure.com:v3/rakeshrakshit/USDesk/USDeskForJava

